-- name: create-users-table
CREATE TABLE "user"
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    username      VARCHAR(128) NOT NULL UNIQUE,
    password      VARCHAR(256) NOT NULL,
    password_salt UUID         NOT NULL DEFAULT gen_random_uuid(),
    token_salt    UUID         NOT NULL DEFAULT gen_random_uuid()
);

-- name: create-task-table
CREATE TABLE "task"
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    title VARCHAR(256) NOT NULL
);